apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    name: httpd-pod
spec:
  nodeName: master
  containers:
    - name: httpd
      image: httpd
      volumeMounts:
        - mountPath: /usr/local/apache2/htdocs/
          name: httpd-storage
  volumes:
    - name: httpd-storage
      persistentVolumeClaim:
        claimName: httpd-pvc
